/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    trainings: Training;
    'pricing-cards': PricingCard;
    principles: Principle;
    opinions: Opinion;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    trainings: TrainingsSelect<false> | TrainingsSelect<true>;
    'pricing-cards': PricingCardsSelect<false> | PricingCardsSelect<true>;
    principles: PrinciplesSelect<false> | PrinciplesSelect<true>;
    opinions: OpinionsSelect<false> | OpinionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    hero: Hero;
    about: About;
    wireframe: Wireframe;
    'green-tactics': GreenTactic;
    contact: Contact;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    wireframe: WireframeSelect<false> | WireframeSelect<true>;
    'green-tactics': GreenTacticsSelect<false> | GreenTacticsSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Pięć dróg, jeden proces — sekcja "Trainings" na stronie głównej.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainings".
 */
export interface Training {
  id: number;
  /**
   * Kolejność wyświetlania (1–5).
   */
  order: number;
  /**
   * Np. "01 / 05 — BAZA".
   */
  numberLabel: string;
  /**
   * Główny tytuł karty, np. "Strzelanie podstawowe".
   */
  title: string;
  /**
   * Część tytułu w akcentowym kolorze (kursywa).
   */
  titleAccent?: string | null;
  /**
   * Druga linia tytułu, np. "precision / long range".
   */
  subtitle?: string | null;
  description: string;
  specs?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Plik wideo do tła karty.
   */
  video?: (number | null) | Media;
  /**
   * Czy video ma być scrubowane scrollem (jak w long-range). Domyślnie autoplay loop.
   */
  scrubVideo?: boolean | null;
  ctaLabel?: string | null;
  /**
   * Wartość przekazywana do formularza kontaktowego (np. "Strzelanie długodystansowe — long range").
   */
  ctaTraining?: string | null;
  /**
   * Anchor HTML (np. "long-range") jeśli sekcja ma być linkowana.
   */
  anchor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sekcja cennika na stronie głównej.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-cards".
 */
export interface PricingCard {
  id: number;
  order: number;
  /**
   * Np. "01".
   */
  numberLabel: string;
  name: string;
  /**
   * Akcentowana część nazwy (kursywa).
   */
  nameAccent?: string | null;
  description: string;
  /**
   * Cena w PLN.
   */
  price: number;
  /**
   * Np. "/ sesja · 2h".
   */
  unit: string;
  features?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wyróżnić jako "Popularne".
   */
  featured?: boolean | null;
  /**
   * Tekst plakietki (np. "Popularne").
   */
  badge?: string | null;
  ctaLabel?: string | null;
  /**
   * Wartość pola "szkolenie" w formularzu kontaktowym.
   */
  ctaTraining?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sekcja "Proces. Nie sztuczki." — zasady pracy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "principles".
 */
export interface Principle {
  id: number;
  order: number;
  /**
   * Np. "01".
   */
  numberLabel: string;
  title: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Opinie kursantów wyświetlane w sekcji opinii.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opinions".
 */
export interface Opinion {
  id: number;
  order: number;
  author: string;
  rating?: number | null;
  quote: string;
  /**
   * Z jakiego szkolenia, np. "Long range".
   */
  training?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'trainings';
        value: number | Training;
      } | null)
    | ({
        relationTo: 'pricing-cards';
        value: number | PricingCard;
      } | null)
    | ({
        relationTo: 'principles';
        value: number | Principle;
      } | null)
    | ({
        relationTo: 'opinions';
        value: number | Opinion;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainings_select".
 */
export interface TrainingsSelect<T extends boolean = true> {
  order?: T;
  numberLabel?: T;
  title?: T;
  titleAccent?: T;
  subtitle?: T;
  description?: T;
  specs?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  video?: T;
  scrubVideo?: T;
  ctaLabel?: T;
  ctaTraining?: T;
  anchor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-cards_select".
 */
export interface PricingCardsSelect<T extends boolean = true> {
  order?: T;
  numberLabel?: T;
  name?: T;
  nameAccent?: T;
  description?: T;
  price?: T;
  unit?: T;
  features?:
    | T
    | {
        item?: T;
        id?: T;
      };
  featured?: T;
  badge?: T;
  ctaLabel?: T;
  ctaTraining?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "principles_select".
 */
export interface PrinciplesSelect<T extends boolean = true> {
  order?: T;
  numberLabel?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opinions_select".
 */
export interface OpinionsSelect<T extends boolean = true> {
  order?: T;
  author?: T;
  rating?: T;
  quote?: T;
  training?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * Małe oznaczenie nad tytułem (np. "01 / Intro").
   */
  kicker?: string | null;
  /**
   * Każda linia tytułu osobno (kolejne linie pojawiają się przy scrollu).
   */
  title?:
    | {
        text: string;
        /**
         * Czy linia ma być w kolorze akcentowym (kursywa).
         */
        accent?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Krótki podtytuł pod nagłówkiem.
   */
  lede?: string | null;
  /**
   * Wideo scrubowane scrollem (hero video).
   */
  video?: (number | null) | Media;
  ctaLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Np. "02 / O mnie".
   */
  kicker?: string | null;
  name: string;
  /**
   * Np. "Instruktor strzelectwa".
   */
  role?: string | null;
  paragraphs?:
    | {
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wideo wyświetlane po lewej stronie sekcji.
   */
  video?: (number | null) | Media;
  /**
   * Alternatywne zdjęcie (jeśli bez video).
   */
  image?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wireframe".
 */
export interface Wireframe {
  id: number;
  kicker?: string | null;
  title: string;
  /**
   * Akcentowana część tytułu.
   */
  titleAccent?: string | null;
  /**
   * Druga linia tytułu.
   */
  subtitle?: string | null;
  description?: string | null;
  /**
   * Etykiety etapów (np. "01 / Spust").
   */
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wideo wireframe scrubowane scrollem.
   */
  video?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "green-tactics".
 */
export interface GreenTactic {
  id: number;
  kicker?: string | null;
  sectionNumber?: string | null;
  title: string;
  titleAccent?: string | null;
  description?: string | null;
  features?:
    | {
        numberLabel: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  video?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  /**
   * Np. "+48 692 ...".
   */
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  mapsUrl?: string | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  navigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Intensywność animacji scroll (1-10) — wpływa na płynność scrubu hero.
   */
  scrollIntensity?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  kicker?: T;
  title?:
    | T
    | {
        text?: T;
        accent?: T;
        id?: T;
      };
  lede?: T;
  video?: T;
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  kicker?: T;
  name?: T;
  role?: T;
  paragraphs?:
    | T
    | {
        body?: T;
        id?: T;
      };
  video?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wireframe_select".
 */
export interface WireframeSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  titleAccent?: T;
  subtitle?: T;
  description?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  video?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "green-tactics_select".
 */
export interface GreenTacticsSelect<T extends boolean = true> {
  kicker?: T;
  sectionNumber?: T;
  title?: T;
  titleAccent?: T;
  description?: T;
  features?:
    | T
    | {
        numberLabel?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  video?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  address?: T;
  mapsUrl?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  scrollIntensity?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}